name: Build with CMake
on: [pull_request]

concurrency:                                                                                                                                                                                                                                  
    group: ${{ github.workflow }}-${{ github.ref }}                                                                                                                                                                                             
    cancel-in-progress: true    

jobs:
    cmake_build_on_ubuntu:
        runs-on: ubuntu-latest
        steps:
            - name: Dependencies
              uses: daaku/gh-action-apt-install@v4
              with:
                packages: zlib1g-dev libjpeg-dev libhdf5-dev
            - name: Checkout on Ubuntu
              uses: actions/checkout@v4
              with:
                fetch-depth: 0 # fetch all history for git describe to work
            - name : Set up Python
              uses: actions/setup-python@v5.1.0
              with:
                python-version: '3.11'
                cache: 'pip'
                cache-dependency-path: 'pyproject.toml'
            - name: Install dependencies
              run:
                python -m pip install --upgrade pip numpy pybind11
            - name: Build on Ubuntu
              uses: threeal/cmake-action@v2.0.0
              with:
                run-build: true
